"""change products model

Revision ID: 33909d6cf68b
Revises: db3e58f6eb07
Create Date: 2026-08-28 03:35:03.212297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33909d6cf68b'
down_revision: Union[str, Sequence[str], None] = 'db3e58f6eb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sum_grade', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('reviews_count', sa.Integer(), nullable=False))
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False))
    op.drop_column('products', 'reviews_count')
    op.drop_column('products', 'sum_grade')
    # ### end Alembic commands ###
