"""Обновление поля role у пользователей

Revision ID: 752dfb27ed16
Revises: 77e2228ce6ba
Create Date: 2026-07-25 05:10:57.274871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752dfb27ed16'
down_revision: Union[str, Sequence[str], None] = '77e2228ce6ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
