"""update products model

Revision ID: db3e58f6eb07
Revises: 511e1967fdc2
Create Date: 2026-08-16 22:49:13.893748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3e58f6eb07'
down_revision: Union[str, Sequence[str], None] = '511e1967fdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_seller_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_seller_id_fkey'), 'products', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###
