from __future__ import annotations

from typing import Any, Protocol


class ILogger(Protocol):

    def bind(self, **context: Any) -> "ILogger": ...

    def debug(self, event: str, **kwargs: Any) -> None: ...

    def info(self, event: str, **kwargs: Any) -> None: ...

    def warning(self, event: str, **kwargs: Any) -> None: ...

    def error(self, event: str, **kwargs: Any) -> None: ...

    def exception(self, event: str, **kwargs: Any) -> None: ...
