from typing import Protocol


class IStateClient(Protocol):
    async def sadd(self, key: str, value: str) -> None: ...
    async def smembers(self, key: str) -> set[str]: ...
    async def delete(self, key: str) -> None: ...
    async def set(self, key: str, value: str, ttl: int) -> None: ...
    async def get(self, key: str) -> str: ...
